# Spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learningjoy?createDatabaseIfNotExist=true
    username: sa
    password: Welcome1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

# Server
server:
  port: 80
  context-path: /LearningJoy/MiniProgram