# Spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learningjoy?createDatabaseIfNotExist=true
    # driverClassName: net.sf.log4jdbc.DriverSpy
    # url: jdbc:log4jdbc:mysql://localhost:3306/wechat?createDatabaseIfNotExist=true
    username: sa
    password: Welcome1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  http:
    multipart:
      max-file-size: 100MB

# Server
server:
  port: 80
  context-path: /LearningJoy/MiniProgram